### ISSUE TITLE
Switch to Vite

### ISSUE THREAD

**Issue by damianstasik** [traceo-dev/traceo#58]
I took a quick peek at the `package.json` for the web app and noticed that you have a lot of dev dependencies for the dev mode and prod builds. I quickly cloned the repo and started experimenting with replacing webpack and react-scripts with just one tool: Vite. It took me just a moment and I had the app up-and-running with just 2 dependencies, replacing these:
- `react-scripts`
- `@babel/plugin-transform-runtime`
- `@babel/core`
- `@babel/preset-typescript`
- `babel-preset-react`
- `copy-webpack-plugin`
- `css-loader`
- `css-minimizer-webpack-plugin`
- `eslint-webpack-plugin`
- `html-loader`
- `html-webpack-plugin`
- `mini-css-extract-plugin`
- `postcss-loader`
- `raw-loader`
- `webpack`
- `webpack-bundle-analyzer`
- `webpack-cli`
- `webpack-dev-server`
- `webpack-merge`

That's just the first benefit, Vite would simplify the project's setup, it has multiple built-in loaders to handle for example CSS and other file types, it has HMR support, it works out of the box with TS and of course it's super fast.

My question is whether you would accept my PR that would replace webpack/react-scripts with Vite. I could have a draft tomorrow for you to take a look and ask any questions.

**Comment by piotr-szewczyk** [comment]
Hi, that sounds good, prepare please PR and I review it
